### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by soufiane-fadil** [xstevens/syslog-kafka#2]
Dear all,

There is documentation or any guideline for this repo ?

Many thanks

**Comment by xstevens** [comment]
@bloodymind Sorry I hadn't got back to you yet. No not really. I wrote a similar thing for a company I used to work for but it was closed source based on Netty. These days I would advise using something like rsyslog's built-in support for pushing data to Kafka. I think syslog-ng has one as well but not sure.

Best of luck!
